"""session versioning, two-factor auth, campaign worker lease

Revision ID: ec0f528a1d04
Revises: 5fe3066a065a
Create Date: 2026-10-04 04:34:30.406902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0f528a1d04'
down_revision = '5fe3066a065a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_owner', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_last_step', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_last_step')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('session_version')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('lease_owner')

    # ### end Alembic commands ###
